services:
  - type: web
    name: deepfake-video-detection
    env: python
    rootDir: DeepFakeVideoDetection
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=1 --threads=1 --timeout=120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"  # Minimizes TensorFlow console output logs to save CPU/memory
